import { StyleSheet, Dimensions } from 'react-native';
import { COLORS, SPACING, RADIUS } from '../../theme';

const { width } = Dimensions.get('window');

export const CIDFlowStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS?.white || '#fff' },
  safeAreaWhite: { flex: 1, backgroundColor: COLORS?.white || '#fff' },
  safeAreaDark: { flex: 1, backgroundColor: '#0f172a' },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 40, flexGrow: 1 },
  centeredContent: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 20 },
  successCircle: {
      width: 80, height: 80, borderRadius: 40, backgroundColor: '#dcfce7', alignItems: 'center', justifyContent: 'center', marginBottom: 20
  },
  checkMark: { fontSize: 40, color: '#16a34a' },
  headingLg: { fontSize: 26, fontWeight: '800', color: COLORS?.textPrimary || '#0f172a', textAlign: 'center' },
  cidCard: { marginTop: 30, paddingVertical: 30, paddingHorizontal: 20, backgroundColor: COLORS?.primaryLight || '#eff6ff', borderRadius: 16, alignItems: 'center' },
  cidCardLabel: { fontSize: 12, color: COLORS?.primary || '#3b82f6', marginBottom: 10, fontWeight: '700', letterSpacing: 1.5 },
  cidFullText: { fontSize: 34, letterSpacing: 6, fontWeight: '800', color: COLORS?.primary || '#3b82f6' },
  cidSubNote: { fontSize: 13, color: COLORS?.textSecondary || '#64748b', marginTop: 12 },
  iconContainer: { width: 90, height: 90, borderRadius: 24, backgroundColor: COLORS?.primary || '#3b82f6', alignItems: 'center', justifyContent: 'center', marginBottom: 30 },
  iconEmoji: { fontSize: 40 },
  spinner: { width: 40, height: 40, borderRadius: 20, borderWidth: 4, borderColor: COLORS?.primary || '#3b82f6', borderTopColor: 'transparent', marginTop: 40 },
  cryptoNote: { fontSize: 13, color: COLORS?.textSecondary || '#64748b', marginTop: 30, textAlign: 'center' },
  subText: { fontSize: 16, color: COLORS?.textSecondary || '#64748b', textAlign: 'center', marginTop: 12, lineHeight: 22 },
  profileCard: { padding: 24, alignItems: 'center', backgroundColor: COLORS?.cardBg || '#f8fafc', borderRadius: 16, marginBottom: 24, borderWidth: 1, borderColor: COLORS?.border || '#e2e8f0' },
  avatarCircle: { width: 70, height: 70, borderRadius: 35, backgroundColor: COLORS?.primaryLight || '#eff6ff', alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  avatarIcon: { fontSize: 32 },
  profileName: { fontSize: 20, fontWeight: '700', color: COLORS?.textPrimary || '#0f172a' },
  profileCID: { fontSize: 16, color: COLORS?.primary || '#3b82f6', marginTop: 4, fontWeight: '600' },
  profileSub: { fontSize: 14, color: COLORS?.textSecondary || '#64748b', marginTop: 8 },
  actionRow: { flexDirection: 'row', alignItems: 'center', padding: 18, backgroundColor: COLORS?.cardBg || '#f8fafc', borderRadius: 14, marginBottom: 12, borderWidth: 1, borderColor: COLORS?.border || '#e2e8f0' },
  actionIcon: { fontSize: 22, marginRight: 16 },
  actionLabel: { flex: 1, fontSize: 16, fontWeight: '600', color: COLORS?.textPrimary || '#0f172a' },
  actionBadge: { fontSize: 14, fontWeight: '700', color: COLORS?.primary || '#3b82f6', marginRight: 12 },
  actionArrow: { fontSize: 20, color: COLORS?.textMuted || '#94a3b8' },
  warningBox: { padding: 16, backgroundColor: '#fef2f2', borderRadius: 12, marginTop: 30, borderWidth: 1, borderColor: '#fecaca' },
  warningText: { fontSize: 14, color: '#dc2626', lineHeight: 20, fontWeight: '500' },
  infoBox: { padding: 16, backgroundColor: '#eff6ff', borderRadius: 12, marginTop: 16, borderWidth: 1, borderColor: '#bfdbfe' },
  infoBoxText: { fontSize: 14, color: '#2563eb', lineHeight: 20 },
  qrWrapper: { alignItems: 'center', marginVertical: 30 },
  qrInner: { padding: 24, backgroundColor: '#fff', borderRadius: 20, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 15, elevation: 8 },
  qrOverlay: { position: 'absolute', top: '50%', left: '50%', width: 48, height: 48, marginTop: -24, marginLeft: -24, backgroundColor: '#fff', borderRadius: 24, alignItems: 'center', justifyContent: 'center' },
  qrLockBadge: { width: 36, height: 36, borderRadius: 18, backgroundColor: COLORS?.primaryLight || '#eff6ff', alignItems: 'center', justifyContent: 'center' },
  qrLockIcon: { fontSize: 18 },
  qrCard: { alignItems: 'center' },
  scannerViewport: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  scannerFrame: { width: width * 0.7, height: width * 0.7, borderWidth: 2, borderColor: 'rgba(255,255,255,0.2)' },
  scannerCorner: { position: 'absolute', width: 40, height: 40, borderColor: COLORS?.primary || '#3b82f6', borderWidth: 4 },
  scanLine: { width: '100%', height: 2, backgroundColor: COLORS?.primary || '#3b82f6' },
  scannerBottom: { position: 'absolute', bottom: 60, width: '100%', alignItems: 'center' },
  scannerHint: { fontSize: 18, fontWeight: '600', color: '#fff', marginBottom: 8 },
  scannerSub: { fontSize: 14, color: '#94a3b8', marginBottom: 30 },
  scannerOr: { fontSize: 14, color: '#94a3b8', marginVertical: 20 },
  enterCIDBtn: { paddingVertical: 16, paddingHorizontal: 30, backgroundColor: 'rgba(255,255,255,0.1)', borderRadius: 100 },
  enterCIDText: { fontSize: 16, fontWeight: '600', color: '#fff', letterSpacing: 1 },
  scannerFrameGreen: { width: width * 0.7, height: width * 0.7, borderWidth: 2, borderColor: 'rgba(16, 185, 129, 0.5)' },
  scanSuccessDot: { width: 60, height: 60, borderRadius: 30, backgroundColor: '#10b981', position: 'absolute', top: '50%', left: '50%', marginLeft: -30, marginTop: -30, alignItems: 'center', justifyContent: 'center' },
  bottomSheet: { position: 'absolute', bottom: 0, width: '100%', backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24 },
  e2eeHint: { padding: 16, backgroundColor: COLORS?.background || '#f1f5f9', borderRadius: 12, marginTop: 20 },
  e2eeHintText: { fontSize: 13, color: COLORS?.textSecondary || '#64748b', textAlign: 'center', lineHeight: 18 },
  cancelText: { fontSize: 16, fontWeight: '600', color: COLORS?.textMuted || '#94a3b8', textAlign: 'center', marginTop: 24 },
  tabRow: { flexDirection: 'row', backgroundColor: COLORS?.background || '#f1f5f9', borderRadius: 12, padding: 4, marginBottom: 24 },
  tab: { flex: 1, paddingVertical: 12, alignItems: 'center', borderRadius: 8 },
  tabActive: { backgroundColor: '#fff', shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 5, elevation: 2 },
  tabText: { fontSize: 15, color: COLORS?.textSecondary || '#64748b', fontWeight: '600' },
  tabTextActive: { color: COLORS?.textPrimary || '#0f172a' },
  fieldLabel: { fontSize: 14, fontWeight: '600', color: COLORS?.textPrimary || '#0f172a', marginBottom: 12 },
  cidInputRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 24 },
  cidInputCell: { width: (width - 40 - 50) / 6, height: 55, borderWidth: 1.5, borderColor: COLORS?.border || '#e2e8f0', borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS?.inputBg || '#f8fafc' },
  pasteRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginBottom: 30 },
  pasteIcon: { fontSize: 20, marginRight: 10 },
  pasteText: { fontSize: 16, fontWeight: '600', color: COLORS?.primary || '#3b82f6' },
  hintBox: { padding: 16, backgroundColor: COLORS?.background || '#f1f5f9', borderRadius: 12 },
  hintText: { fontSize: 14, color: COLORS?.textSecondary || '#64748b', textAlign: 'center', lineHeight: 20 },
  orShareCID: { marginTop: 24, alignItems: 'center' },
  orShareText: { fontSize: 16, fontWeight: '600', color: COLORS?.primary || '#3b82f6' },
  secondaryActionBtn: { paddingVertical: 16, borderRadius: 100, borderWidth: 1.5, borderColor: COLORS?.border || '#e2e8f0', alignItems: 'center', marginTop: 16 },
  secondaryActionText: { fontSize: 16, color: COLORS?.textPrimary || '#0f172a', fontWeight: '700' },
});
